[package]
name = "RBR-Telemetry-Viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy_channel_trigger = "0.5.0"
bevy_simple_text_input = "0.12.0"
bincode = "2.0.1"
serde = "1.0.228"

[profile.dev]
incremental = true
debug = 0

